plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
  - sub_pages/mobilization.md
  - sub_pages/communities.md

theme: jekyll-theme-minimal
title: Community Playbook
description: https://voice.mozilla.org
logo: /assets/img/logo.png
show_downloads: true
