plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
  - sub_pages/mobilization.md
  - sub_pages/communities.md


theme: jekyll-theme-minimal
title:  Mozilla Common Voice Community Playbook 
description: https://commonvoice.mozilla.org
logo: /assets/img/logo.png
show_downloads: true
